# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_function_A_cpp <- function(x) {
    .Call(`_DATA5012025Assignment1Q2_my_function_A_cpp`, x)
}

my_function_B_cpp <- function(x) {
    .Call(`_DATA5012025Assignment1Q2_my_function_B_cpp`, x)
}

